# Generated by Django 4.1.2 on 2022-11-16 22:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='perfil',
            name='Avatar',
            field=models.ImageField(blank=True, default='Avatares/default.png', upload_to='Avatares'),
        ),
        migrations.AlterField(
            model_name='perfil',
            name='banner',
            field=models.ImageField(blank=True, default='banners/banner.png', upload_to='banners'),
        ),
    ]
