# Generated by Django 4.1.2 on 2022-11-26 11:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Users', '0003_administrador'),
    ]

    operations = [
        migrations.AddField(
            model_name='administrador',
            name='direccion',
            field=models.CharField(default=1, max_length=254),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='administrador',
            name='telefono',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
