# Generated by Django 4.1.2 on 2022-11-28 01:13

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('Mensage', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='sugerencia',
            name='mensaje_id',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Id_mensaje_personal'),
            preserve_default=False,
        ),
    ]
