# Generated by Django 4.1.3 on 2022-11-28 01:01

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('PControl', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='supervisor',
            name='user_id',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='personaldxtv',
            name='user_id',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='personalcc',
            name='user_id',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='horas_trabajadas',
            name='personal1',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='PControl.personaldxtv'),
        ),
        migrations.AddField(
            model_name='dias_trabajados',
            name='personal',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Personal_PersonalCC', to='PControl.personalcc'),
        ),
    ]
