# Generated by Django 4.1.2 on 2022-11-26 11:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('PControl', '0004_personalcc_direccion_personalcc_telefono_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='supervisor',
            name='direccion',
            field=models.CharField(default=1, max_length=254),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='supervisor',
            name='telefono',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='dias_trabajados',
            name='personal',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Personal_PersonalCC', to='PControl.personalcc'),
        ),
    ]
